# Generated by Django 3.0.7 on 2020-06-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_auto_20200619_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expediente',
            options={'ordering': ['idExpediente'], 'verbose_name': 'Expediente', 'verbose_name_plural': 'Expedientes'},
        ),
        migrations.AlterField(
            model_name='expediente',
            name='obserpsi',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Observaciones Psicologicas'),
        ),
    ]
